/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

'use strict';

// some of the alexa US top 50 sites and subpages
module.exports = [
  { url: 'https://www.google.com/?gws_rd=ssl',
    title: 'Google' },
  { url: 'https://www.facebook.com/TheSimpsons',
    title: 'The Simpsons | Facebook' },
  { url: 'https://www.facebook.com/TheSimpsons/videos?ref=page_internal',
    title: 'The Simpsons - Videos | Facebook' },
  { url: 'https://www.facebook.com/TheSimpsons/photos_stream?ref=page_internal',
    title: 'The Simpsons - Photos | Facebook' },
  { url: 'https://www.facebook.com/TheSimpsons/info?ref=page_internal',
    title: 'The Simpsons - About | Facebook' },
  { url: 'https://www.facebook.com/TheSimpsons/events?ref=page_internal',
    title: 'The Simpsons - Events | Facebook' },
  { url: 'https://www.youtube.com/',
    title: 'YouTube' },
  { url: 'https://www.youtube.com/watch?v=kvptRAfYpWM',
    title: 'Can - Paperhouse 1971 (Tago Mago) - YouTube' },
  { url: 'https://www.linkedin.com/',
    title: 'World\'s Largest Professional Network | LinkedIn' },
  { url: 'http://www.amazon.com/',
    title: 'Amazon.com: Online Shopping for Electronics, Apparel, Computers, Books, DVDs & more' },
  { url: 'http://www.amazon.com/s/ref=nb_sb_noss/192-8155327-3884911?url=search-alias%3Daps&field-keywords=silly+string+gun',
    title: 'Amazon.com: silly string gun' },
  { url: 'http://www.amazon.com/Silly-Crazy-String-Gun-Blaster/dp/B00EQ8HUHS/ref=sr_1_1?ie=UTF8&qid=1422476757&sr=8-1&keywords=silly+string+gun',
    title: 'Amazon.com: Silly Crazy String Gun - Party String Blaster Gun: Toys & Games' },
  { url: 'http://www.amazon.com/s/ref=nb_sb_noss_2?url=search-alias%3Daps&field-keywords=javascript%20',
    title: 'Amazon.com: javascript' },
  { url: 'http://www.amazon.com/Professional-JavaScript-Developers-Nicholas-Zakas/dp/1118026691/ref=sr_1_14?ie=UTF8&qid=1422476771&sr=8-14&keywords=javascript',
    title: 'Professional JavaScript for Web Developers: Nicholas C. Zakas: 9781118026694: Amazon.com: Books' },
  { url: 'https://search.yahoo.com/yhs/search?p=javascript+books&ei=UTF-8&hspart=mozilla&hsimp=yhs-001',
    title: 'javascript books - - Yahoo Search Results' },
  { url: 'http://finance.yahoo.com/',
    title: 'Yahoo Finance - Business Finance, Stock Market, Quotes, News' },
  { url: 'http://finance.yahoo.com/q?s=yhoo&fr=uh3_finance_web&uhb=uhb2',
    title: 'YHOO: Summary for Yahoo! Inc.- Yahoo! Finance' },
  { url: 'http://en.wikipedia.org/w/index.php?search=javascript+scope&title=Special%3ASearch&go=Go',
    title: 'javascript scope - Search results - Wikipedia, the free encyclopedia' },
  { url: 'https://www.linkedin.com/today/author/204068115-Richard-Branson',
    title: 'Richard Branson | LinkedIn Influencer | LinkedIn' },
  { url: 'http://en.wikipedia.org/wiki/Troma_Entertainment',
    title: 'Troma Entertainment - Wikipedia, the free encyclopedia' },
  { url: 'http://en.wikipedia.org/wiki/JavaScript',
    title: 'JavaScript - Wikipedia, the free encyclopedia' },
  { url: 'https://twitter.com/mozilla',
    title: 'Mozilla (@mozilla) | Twitter' },
  { url: 'http://t.co/DKiimCLEUR',
    title: 'http://twitter.com/mozilla/status/560513225872392192/photo/1' },
  { url: 'http://www.ebay.com/',
    title: 'Electronics, Cars, Fashion, Collectibles, Coupons and More | eBay' },
  { url: 'http://www.ebay.com/rpp/sports-mem',
    title: 'Sports Memorabilia - Memorabilia, Cards, Autographs & more | eBay' },
  { url: 'http://www.ebay.com/rpp/collectibles-live-auctions',
    title: 'eBay | Live Auctions & Events - Premium Auction Houses' },
  { url: 'http://www.reddit.com/r/adviceanimals',
    title: 'reddit\'s gold mine.' },
  { url: 'http://www.reddit.com/r/javascript',
    title: 'JavaScript' },
  { url: 'http://www.reddit.com/r/javascript/comments/2u00ys/i_have_never_used_javascript_and_have_no_idea/',
    title: 'I have never used javascript and have no idea what im doing! Need help tho : javascript' },
  { url: 'https://www.linkedin.com/pulse/discover',
    title: 'Pulse Discover | LinkedIn' },
  { url: 'https://www.linkedin.com/in/rbranson?trk=mp-ph-pn',
    title: 'Richard Branson | LinkedIn' },
  { url: 'http://sfbay.craigslist.org/search/apa',
    title: 'SF bay area apts/housing for rent - craigslist' },
  { url: 'http://sfbay.craigslist.org/search/apa#list',
    title: 'SF bay area apts/housing for rent - craigslist' },
  { url: 'http://imgur.com/',
    title: 'imgur: the simple image sharer' },
  { url: 'http://imgur.com/gallery/APKFK4i',
    title: 'Wind made a double helix in the snow - Imgur' },
  { url: 'http://go.com/',
    title: 'Go.com | The Walt Disney Company ' },
  { url: 'http://abcnews.go.com/international',
    title: 'International News | World News - ABC News' },
  { url: 'http://abcnews.go.com/topics/news/ukraine.htm',
    title: 'Ukraine News, Photos and Videos - ABC News' },
  { url: 'http://abcnews.go.com/International/wireStory/russian-govt-proposes-spending-cuts-view-crisis-28540813',
    title: 'Russian Government Details Spending Cuts in View of Crisis - ABC News' },
  { url: 'https://www.tumblr.com/',
    title: 'Sign up | Tumblr' },
  { url: 'http://mozillachronicle.tumblr.com/',
    title: 'Mozilla Chronicle' },
  { url: 'http://mozillachronicle.tumblr.com/post/104443045652/it-begins',
    title: 'Mozilla Chronicle — It Begins' },
  { url: 'https://www.netflix.com/us/',
    title: 'Netflix - Watch TV Shows Online, Watch Movies Online' },
  { url: 'https://www.pinterest.com/',
    title: 'Pinterest' },
  { url: 'https://www.pinterest.com/explore/most-popular/',
    title: 'Most Popular on Pinterest' },
  { url: 'http://espn.go.com/',
    title: 'ESPN: The Worldwide Leader In Sports' }
];
